# Generated by Django 4.2.8 on 2023-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_bookmark_site_name_alter_bookmark_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, default='Не найден', max_length=3000, verbose_name='Краткое описания'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='og_image',
            field=models.ImageField(default='Не найден', upload_to='photos/%Y/%m/%d/', verbose_name='Фото Open Graph'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='site_name',
            field=models.CharField(default='Не найден', max_length=255, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(default='Не найден', max_length=255, verbose_name='Название'),
        ),
    ]
